"""Declarative base for every GPCA table.

Two things are set here that are painful to retrofit once migrations exist:
the constraint naming convention and the annotation-to-column type map. Both
must be correct in the first migration -- see docs/technical-design.md 12.4.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData, Numeric, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic names for every index and constraint. Without this, PostgreSQL
# invents names for unnamed constraints, Alembic cannot reliably reference them,
# and autogenerated downgrades end up unable to drop what upgrades created.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all models.

    Importing this module must not open a database connection: it declares
    metadata only. The engine is constructed separately in session.py.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Maps a Python annotation to the column type it produces, so models can
    # write `Mapped[datetime]` and get a timezone-aware column every time.
    # Naive timestamps are the single most common source of off-by-hours bugs,
    # so the mapping never yields a bare TIMESTAMP.
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: DateTime(timezone=True),
        Decimal: Numeric(12, 2),
        dict[str, Any]: JSONB,
    }


class TimestampMixin:
    """Adds `created_at` / `updated_at` to a model.

    Both default server-side, so rows inserted by a migration or by raw SQL are
    stamped too. `onupdate` is applied by SQLAlchemy on ORM and Core updates;
    a statement issued outside SQLAlchemy will not refresh `updated_at`. If a
    table ever needs that guarantee, it wants a database trigger instead.
    """

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
