"""Declarative base for every GPCA table.

Two things are set here that are painful to retrofit once migrations exist:
the constraint naming convention and the annotation-to-column type map. Both
must be correct in the first migration -- see docs/technical-design.md 12.4.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any, ClassVar

from sqlalchemy import DateTime, Index, MetaData, Numeric, Table, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _index_prefix(index: Index, _table: Table) -> str:
    """`uq` for a unique index, `ix` for an ordinary one.

    PostgreSQL cannot express a partial or expression-based UNIQUE constraint,
    so uniqueness of that shape has to be a unique Index instead -- which
    SQLAlchemy would otherwise name `ix_...`, reading as a plain lookup index.
    This makes the prefix follow what the object *does* rather than which
    class declared it, so `uq_` still means "enforces uniqueness" whether it
    came from a UniqueConstraint or an Index.

    It applies only where a name was not supplied. A partial index is often
    clearer named by hand -- `uq_auth_tokens_user_purpose_live` says which
    rows it covers, and no template can derive that from the columns -- so an
    explicit name still wins. This is the floor, not the house style.
    """
    return "uq" if index.unique else "ix"


# Deterministic names for every index and constraint. Without this, PostgreSQL
# invents names for unnamed constraints, Alembic cannot reliably reference them,
# and autogenerated downgrades end up unable to drop what upgrades created.
#
# `index_prefix` is a custom token: SQLAlchemy calls it with (index, table) and
# substitutes the result wherever %(index_prefix)s appears.
NAMING_CONVENTION: dict[str, Any] = {
    "index_prefix": _index_prefix,
    "ix": "%(index_prefix)s_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all models.

    Importing this module must not open a database connection: it declares
    metadata only. The engine is constructed separately in session.py.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Maps a Python annotation to the column type it produces, so models can
    # write `Mapped[datetime]` and get a timezone-aware column every time.
    # Naive timestamps are the single most common source of off-by-hours bugs,
    # so the mapping never yields a bare TIMESTAMP.
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: DateTime(timezone=True),
        Decimal: Numeric(12, 2),
        dict[str, Any]: JSONB,
    }


class TimestampMixin:
    """Adds `created_at` / `updated_at` to a model.

    Both default server-side, so rows inserted by a migration or by raw SQL are
    stamped too. `onupdate` is applied by SQLAlchemy on ORM and Core updates;
    a statement issued outside SQLAlchemy will not refresh `updated_at`. If a
    table ever needs that guarantee, it wants a database trigger instead.
    """

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
